---
# common
document_root: '/var/www/html/htdocs'

# WordPress
wordpress_site_name: 'wordprss test site'
wordpress_directory: '/wp' # like '/wp'
wordpress_db_name: 'wp_test'
wordpress_db_user: 'wp_test'
wordpress_db_password: 'password'
wordpress_db_prefix: 'wptest_'
wordpress_site_admin_user: 'admin'
wordpress_site_admin_password: 'adminpass'
wordpress_site_admin_email: 'ogura@ingsnet.co.jp'